FROM amazonlinux:latest
# Update yum and install pre-reqs for builds
RUN yum update -y -q \
    # pre-reqs for sqlite
    && yum install -y -q tar gzip make gcc expectk readline-devel yum-utils \
    # pre-req for aws-cli
    && yum install -y -q unzip \
    # pre-req for zap
    && amazon-linux-extras install docker epel \
    && yum install -y -q wget xmlstarlet java-latest-openjdk \
    && yum clean all
RUN ARCH=$(uname -p) \
    && curl -s "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip" -o "/awscliv2.zip" \
    && unzip -q /awscliv2.zip \
    && rm -f /awscliv2.zip \
    && ./aws/install --bin-dir /aws-cli-bin/
RUN curl -s 'https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release' | tar zx \
    && cd sqlite \
    && ./configure \
    && make
RUN ARCH=$(if [[ `uname -p` = "aarch64" || `uname -p` = "arm64" ]]; then echo "arm64"; else echo "amd64"; fi) \
    && curl -s https://releases.hashicorp.com/terraform/1.2.8/terraform_1.2.8_linux_${ARCH}.zip -o /terraform.zip \
    && unzip -q /terraform.zip
RUN mkdir /zap
WORKDIR /zap
# Download and expand the latest stable release
RUN wget -qO- https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml \
    | xmlstarlet sel -t -v //url | grep -i Linux \
    | wget --content-disposition -i - -qO - | tar zx \
    && mv ZAP*/* . \
    && rm -R ZAP*
# Update add-ons - for some reason this dies on arm64 on github actions
RUN if [[ `uname -p` != "aarch64" ]]; then ./zap.sh -cmd -addonupdate; fi
# Copy them to installation directory
RUN cp /root/.ZAP/plugin/*.zap plugin/ || :
# Setup Webswing
# RUN curl -s -L  "https://dev.webswing.org/files/public/webswing-examples-eval-22.1.3-distribution.zip" -o webswing.zip \
# 	&& unzip -q webswing.zip \
# 	&& rm webswing.zip \
# 	&& mv webswing-* webswing \
# 	# Remove Webswing bundled examples
# 	&& rm -Rf webswing/apps/
