FROM amazonlinux:latest
# Update yum and install pre-reqs for builds
RUN yum update -y -q \
    # pre-reqs for sqlite
    && yum install -y -q tar gzip make gcc expectk readline-devel yum-utils \
    # pre-req for aws-cli
    && yum install -y -q unzip \
    # pre-req for zap
    && amazon-linux-extras install docker epel \
    && yum install -y -q wget xmlstarlet \
    && yum clean all
RUN ARCH=$(uname -p) \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip" -o "/awscliv2.zip" \
    && unzip -q /awscliv2.zip \
    && rm -f /awscliv2.zip \
    && ./aws/install --bin-dir /aws-cli-bin/
RUN curl -o /sqlite.tgz https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release \
    && tar zxf /sqlite.tgz \
    && cd sqlite \
    && ./configure \
    && make
RUN ARCH=$(if [[ `uname -p` = "aarch64" || `uname -p` = "arm64" ]]; then echo "arm64"; else echo "amd64"; fi) \
    && curl https://releases.hashicorp.com/terraform/1.2.8/terraform_1.2.8_linux_${ARCH}.zip -o /terraform.zip \
    && unzip /terraform.zip
RUN mkdir /zap
WORKDIR /zap
# Download and expand the latest stable release
RUN wget -qO- https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml | xmlstarlet sel -t -v //url |grep -i Linux | wget --content-disposition -i - -O - | tar zxv && \
	mv ZAP*/* . && \
	rm -R ZAP*
# Update add-ons
RUN uname -p
RUN if [[ `uname -p` = "aarch64" || `uname -p` = "arm64" ]]; then echo "arm64 does not work yet"; else ./zap.sh -cmd -silent -addonupdate; fi
# Copy them to installation directory
RUN cp /root/.ZAP/plugin/*.zap plugin/ || :
# Setup Webswing
ENV WEBSWING_VERSION 22.1.3
ARG WEBSWING_URL=""
RUN if [ -z "$WEBSWING_URL" ] ; \
	then curl -s -L  "https://dev.webswing.org/files/public/webswing-examples-eval-${WEBSWING_VERSION}-distribution.zip" > webswing.zip; \
	else curl -s -L  "$WEBSWING_URL-${WEBSWING_VERSION}-distribution.zip" > webswing.zip; fi && \
	unzip -q webswing.zip && \
	rm webswing.zip && \
	mv webswing-* webswing && \
	# Remove Webswing bundled examples
	rm -Rf webswing/apps/
